### ISSUE TITLE
Public release

### ISSUE THREAD

**Issue by ManifoldFR** [Simple-Robotics/proxsuite-nlp#35]
# Public release

### Core
- [x] rename class `SolverTpl` and files `solver-base.h**`
- [x] rename main library in in CMake from proxnlp to proxsuite-nlp/proxsuite::nlp
- [x] change includes to `proxsuite-nlp/*`
- [x] change namespace to `proxsuite::nlp`
- [x] use proxsuite-nlp in README.md
- [x] change all the macros prefixed with `PROXNLP_***`
- [x] change all compile definitions prefixed with `PROXNLP_***`

### Meta

- [x] Fix CI to use GitHub CI
- [x] Conda packaging
- [x] Add license file
- [x] Add changelog
- [x] Add contributors to README
- [x] Standardize pre-commit
- [x] Change project name
- [x] Change default branch to main
- [x] Add issue template

### Bindings

- [x] change directory `python/` to `bindings/python/`
- [x] change module name from `proxnlp` to `proxsuite-nlp`
- [x] #44

**Comment by fabinsch** [comment]
@ManifoldFR similar to [proxsuite](https://github.com/Simple-Robotics/proxsuite/blob/main/LICENSE) BSD 2 ?

**Comment by ManifoldFR** [comment]
> @ManifoldFR similar to [proxsuite](https://github.com/Simple-Robotics/proxsuite/blob/main/LICENSE) BSD 2 ?

yep that's what we ended up going with ! :)
